services:
  postgres:
    image: postgres:17.1
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5432
      POSTGRES_DB: rent_your_dreams
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ryd

  configserver:
    image: "rafalciesla/ryd-configserver:latest"
    container_name: configserver
    ports:
      - "8071:8071"
    extends:
      file: docker-private-config.yml
      service: git-authorized
    healthcheck:
      test: "wget -T5 -qO- localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ryd

  eurekaserver:
    image: "rafalciesla/ryd-eurekaserver:latest"
    container_name: eurekaserver
    ports:
      - "8070:8070"
    healthcheck:
      test: "wget -T5 -qO- localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ryd

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 10s
      retries: 10
    networks:
      - ryd

  gatewayserver:
    image: "rafalciesla/ryd-gatewayserver:latest"
    container_name: gatewayserver
    ports:
      - "8072:8072"
    environment:
      SPRING_CONFIG_HOST: "http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_DATA_REDIS_HOST: "redis"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka"
    healthcheck:
      test: "wget -T5 -qO- localhost:8072/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ryd

  users:
    image: "rafalciesla/ryd-users:latest"
    container_name: ryd-users
    ports:
      - "8101:8101"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/rent_your_dreams"
      SPRING_CONFIG_HOST: "http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: "dev"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka"
    depends_on:
      postgres:
        condition: service_healthy
      gatewayserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ryd

  cars:
    image: "rafalciesla/ryd-cars:latest"
    container_name: ryd-cars
    ports:
      - "8102:8102"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/rent_your_dreams"
      SPRING_CONFIG_HOST: "http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: "dev"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka"
    depends_on:
      postgres:
        condition: service_healthy
      gatewayserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ryd

  images:
    image: "rafalciesla/ryd-images:latest"
    container_name: ryd-images
    ports:
      - "8103:8103"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/rent_your_dreams"
      SPRING_CONFIG_HOST: "http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: "dev"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka"
    depends_on:
      postgres:
        condition: service_healthy
      gatewayserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ryd

networks:
  ryd:
    driver: "bridge"

volumes:
  pgdata:
    external: false