server:
  port: 8101
spring:
  application:
    name: users
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:users
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
kapt:
  include:
    compile:
      classpath: false