server:
  port: 8102
spring:
  application:
    name: cars
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:cars
    username: sa
    password: 1234
    driverClassName: org.h2.Driver