server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/rafalciesla/rent-your-dreams-2024-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true