server:
  port: 8074
spring:
  application:
    name: notifications
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        email-in-0:
          destination: send-communication
          group: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    connection-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}